{{- if .Values.useSecurity -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tarantool.fullname" . }}
  labels:
    app: {{ template "tarantool.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.tarantoolPassword }}
  tarantool-password: {{ .Values.tarantoolPassword | b64enc | quote }}
  {{- else }}
  tarantool-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  tarantool-user: {{ .Values.tarantoolUser | b64enc | quote }}
{{- end -}}
